config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :missions
  resources :publications
  resources :projects
  resources :groups
  resources :units
  resources :laboratories
  ActiveAdmin.routes(self)
  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get '/collaboration', :to => 'home#index'
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :abstract
  validates_presence_of :highlights
  validates_presence_of :user_id

end

app/controllers/publications_controller.rb
class PublicationsController < InheritedResources::Base

  private

    def publication_params
      params.require(:publication).permit(:title, :abstract, :highlights, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(publication) do |f| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :abstract %>
    <%= f.text_area :abstract %>
  </div>

  <div class="field">
    <%= f.label :highlights %>
    <%= f.text_area :highlights %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Abstract</th>
      <th>Highlights</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.title %></td>
        <td><%= publication.abstract %></td>
        <td><%= publication.highlights %></td>
        <td><%= publication.user %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @publication.abstract %>
</p>

<p>
  <strong>Highlights:</strong>
  <%= @publication.highlights %>
</p>

<p>
  <strong>User:</strong>
  <%= @publication.user %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>