config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :missions
  resources :publications
  resources :projects
  resources :groups
  resources :units
  resources :laboratories
  ActiveAdmin.routes(self)
  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get '/collaboration', :to => 'home#index'
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :laboratory
  validates_presence_of :name 
  validates_presence_of :description
  validates_presence_of :laboratory_id
end

app/controllers/units_controller.rb
class UnitsController < InheritedResources::Base

  private

    def unit_params
      params.require(:unit).permit(:name, :description, :laboratory_id)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(unit) do |f| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :laboratory_id %>
    <%= f.text_field :laboratory_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Laboratory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.description %></td>
        <td><%= unit.laboratory %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @unit.description %>
</p>

<p>
  <strong>Laboratory:</strong>
  <%= @unit.laboratory %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>